filebeat.inputs:
  - type: filestream
    id: nginx-json-access
    enabled: true
    paths:
      - /var/log/nginx/waf-access.log
    prospector.scanner.check_interval: 1s
    fields:
      log_type: access
    fields_under_root: true

processors:
  - add_fields:
      target: ""
      fields:
        log_type: access

output.kafka:
  hosts: ["kafka:9092"]
  topic: raw-web-logs
  codec.json:
    pretty: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  partition.round_robin:
    reachable_only: false

setup.ilm.enabled: false
setup.template.enabled: false
setup.dashboards.enabled: false

logging.level: info
logging.to_files: false
logging.to_stderr: true
