-- WAF Log Analyzer — MVP schema
-- Source of truth: docs/solution-design.md v1.6 §7.1 / §7.3
--
-- applications 1──N web_events 1──N detection_hits N──1 detection_rules
--                     │
--                     1
--                     │
--                     1 alerts N──1 incidents
--
-- Alert is 1-1 with WebEvent and may be unattached (incident_id NULL)
-- until Incident Manager promotes it (IMMEDIATE / AGGREGATE).

-- ---------------------------------------------------------------------------
-- applications — host → app_id scope (Juice Shop MVP, DVWA = phase 2)
-- ---------------------------------------------------------------------------
CREATE TABLE applications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128)  NOT NULL,
    host_pattern    VARCHAR(255)  NOT NULL,
    risk_threshold  INTEGER       NOT NULL DEFAULT 60,
    enabled         BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_applications_host_pattern UNIQUE (host_pattern),
    CONSTRAINT chk_applications_risk_threshold
        CHECK (risk_threshold BETWEEN 0 AND 100)
);

COMMENT ON TABLE  applications IS 'Monitored app scope. Normalize maps request host → app_id via host_pattern (regex).';
COMMENT ON COLUMN applications.host_pattern IS 'Java/PostgreSQL regex matched against Nginx host (e.g. juice.lab.local).';
COMMENT ON COLUMN applications.risk_threshold IS 'Alert when WebEvent.risk_score >= this value. Default 60 (§7.4).';

-- ---------------------------------------------------------------------------
-- detection_rules — runtime signatures (seeded from detection-rule-generator)
-- ---------------------------------------------------------------------------
CREATE TABLE detection_rules (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(64)   NOT NULL,
    name                VARCHAR(255)  NOT NULL,
    category            VARCHAR(32)   NOT NULL,
    pattern             TEXT          NOT NULL,
    target_field        VARCHAR(16)   NOT NULL,
    weight              INTEGER       NOT NULL,
    enabled             BOOLEAN       NOT NULL DEFAULT TRUE,
    description         TEXT,
    source              VARCHAR(16)   NOT NULL DEFAULT 'AI_MINED',
    generator_rule_id   VARCHAR(64),
    rule_version        VARCHAR(32),

    CONSTRAINT uq_detection_rules_code UNIQUE (code),
    CONSTRAINT chk_detection_rules_category
        CHECK (category IN ('SQLI', 'XSS', 'PATH_TRAVERSAL')),
    CONSTRAINT chk_detection_rules_target_field
        CHECK (target_field IN ('path', 'query', 'ua', 'raw')),
    CONSTRAINT chk_detection_rules_source
        CHECK (source IN ('HAND', 'AI_MINED')),
    CONSTRAINT chk_detection_rules_weight
        CHECK (weight BETWEEN 0 AND 100)
);

COMMENT ON TABLE  detection_rules IS 'Compiled Java regex rules. Provenance: source, generator_rule_id, rule_version (§7.3.6).';
COMMENT ON COLUMN detection_rules.target_field IS 'Access-log field only: path | query | ua | raw (lowercase).';
COMMENT ON COLUMN detection_rules.source IS 'AI_MINED from rule-generator; HAND for manual supplements.';

CREATE INDEX idx_detection_rules_enabled  ON detection_rules (enabled) WHERE enabled = TRUE;
CREATE INDEX idx_detection_rules_category ON detection_rules (category);

-- ---------------------------------------------------------------------------
-- web_events — canonical Nginx JSON access log (§5.4 / §7.1)
-- ---------------------------------------------------------------------------
CREATE TABLE web_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id       BIGINT        NOT NULL REFERENCES applications (id),
    event_time   TIMESTAMPTZ   NOT NULL,
    client_ip    VARCHAR(64)   NOT NULL,
    method       VARCHAR(16)   NOT NULL,
    path         TEXT          NOT NULL,
    query        TEXT,
    status       INTEGER       NOT NULL,
    user_agent   TEXT,
    referer      TEXT,
    raw_ref      TEXT,
    host         VARCHAR(255)  NOT NULL,
    risk_score   INTEGER       NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_web_events_status
        CHECK (status BETWEEN 100 AND 599),
    CONSTRAINT chk_web_events_risk_score
        CHECK (risk_score BETWEEN 0 AND 100)
);

COMMENT ON TABLE  web_events IS 'Normalized in-process from Kafka raw-web-logs. risk_score written after RuleEngine + Scorer.';
COMMENT ON COLUMN web_events.raw_ref IS 'Optional pointer to the raw Kafka record (topic-partition-offset) or Filebeat metadata.';
COMMENT ON COLUMN web_events.risk_score IS '0–100 = min(100, base + freq_bonus(5m) + status_bonus) (§7.4).';

CREATE INDEX idx_web_events_app_time      ON web_events (app_id, event_time DESC);
CREATE INDEX idx_web_events_client_time   ON web_events (client_ip, event_time DESC);
CREATE INDEX idx_web_events_host          ON web_events (host);
CREATE INDEX idx_web_events_score         ON web_events (risk_score DESC);

-- ---------------------------------------------------------------------------
-- detection_hits — one row per (event, rule) match; evidence = matched snippet
-- ---------------------------------------------------------------------------
CREATE TABLE detection_hits (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT        NOT NULL REFERENCES web_events (id) ON DELETE CASCADE,
    rule_id      BIGINT        NOT NULL REFERENCES detection_rules (id),
    evidence     TEXT          NOT NULL,
    weight       INTEGER       NOT NULL,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_detection_hits_event_rule UNIQUE (event_id, rule_id),
    CONSTRAINT chk_detection_hits_weight CHECK (weight BETWEEN 0 AND 100)
);

COMMENT ON COLUMN detection_hits.weight IS 'Copied from detection_rules.weight at hit time so later CRUD does not rewrite history.';
COMMENT ON COLUMN detection_hits.evidence IS 'Substring that matched the regex (for SOC drill-down / LLM explain).';

CREATE INDEX idx_detection_hits_event ON detection_hits (event_id);
CREATE INDEX idx_detection_hits_rule  ON detection_hits (rule_id);

-- ---------------------------------------------------------------------------
-- incidents — correlation key (app_id, client_ip); 1 incident : N alerts
-- Created before alerts so alerts.incident_id can FK here.
-- ---------------------------------------------------------------------------
CREATE TABLE incidents (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id                   BIGINT        NOT NULL REFERENCES applications (id),
    client_ip                VARCHAR(64)   NOT NULL,
    severity                 VARCHAR(16)   NOT NULL,
    score                    INTEGER       NOT NULL,
    alert_count              INTEGER       NOT NULL DEFAULT 0,
    title                    VARCHAR(255)  NOT NULL,
    status                   VARCHAR(16)   NOT NULL DEFAULT 'OPEN',
    promote_reason           VARCHAR(16)   NOT NULL,
    explanation              TEXT,
    explanation_confidence   VARCHAR(16),
    explanation_status       VARCHAR(16)   NOT NULL DEFAULT 'PENDING',
    explanation_error        TEXT,
    explained_at             TIMESTAMPTZ,
    opened_at                TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_incidents_severity
        CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT chk_incidents_status
        CHECK (status IN ('OPEN', 'ACK', 'CLOSED')),
    CONSTRAINT chk_incidents_promote_reason
        CHECK (promote_reason IN ('IMMEDIATE', 'AGGREGATE')),
    CONSTRAINT chk_incidents_explanation_confidence
        CHECK (explanation_confidence IS NULL
            OR explanation_confidence IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_incidents_explanation_status
        CHECK (explanation_status IN ('PENDING', 'READY', 'FAILED', 'SKIPPED')),
    CONSTRAINT chk_incidents_score
        CHECK (score BETWEEN 0 AND 100),
    CONSTRAINT chk_incidents_alert_count
        CHECK (alert_count >= 0)
);

COMMENT ON TABLE  incidents IS 'SOC triage object. IMMEDIATE = CRITICAL; AGGREGATE = MEDIUM/HIGH with K=3 in window W=5m (§7.5).';
COMMENT ON COLUMN incidents.severity IS 'max(member alert severities); updated when a new alert is attached.';
COMMENT ON COLUMN incidents.score IS 'max(member alert scores).';
COMMENT ON COLUMN incidents.explanation_status IS 'LLM async: PENDING → READY|FAILED; SKIPPED when profile llm is off.';

CREATE INDEX idx_incidents_app_status   ON incidents (app_id, status, opened_at DESC);
CREATE INDEX idx_incidents_explain      ON incidents (explanation_status);
CREATE INDEX idx_incidents_open_key     ON incidents (app_id, client_ip, opened_at DESC)
    WHERE status = 'OPEN';

-- ---------------------------------------------------------------------------
-- alerts — 1-1 with web_events; incident_id NULL until promoted
-- ---------------------------------------------------------------------------
CREATE TABLE alerts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id        BIGINT        NOT NULL REFERENCES applications (id),
    event_id      BIGINT        NOT NULL REFERENCES web_events (id),
    incident_id   BIGINT        REFERENCES incidents (id) ON DELETE SET NULL,
    client_ip     VARCHAR(64)   NOT NULL,
    severity      VARCHAR(16)   NOT NULL,
    score         INTEGER       NOT NULL,
    title         VARCHAR(255)  NOT NULL,
    summary       TEXT,
    status        VARCHAR(16)   NOT NULL DEFAULT 'OPEN',
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_alerts_event UNIQUE (event_id),
    CONSTRAINT chk_alerts_severity
        CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT chk_alerts_status
        CHECK (status IN ('OPEN', 'ACK', 'CLOSED')),
    CONSTRAINT chk_alerts_score
        CHECK (score BETWEEN 0 AND 100)
);

COMMENT ON TABLE  alerts IS 'Created when score >= application.risk_threshold. Always persisted; only a subset is promoted to an Incident.';
COMMENT ON COLUMN alerts.incident_id IS 'NULL = not yet promoted (AGGREGATE count < K).';

CREATE INDEX idx_alerts_app_time      ON alerts (app_id, created_at DESC);
CREATE INDEX idx_alerts_incident      ON alerts (incident_id);
CREATE INDEX idx_alerts_status        ON alerts (status);
CREATE INDEX idx_alerts_unattached    ON alerts (app_id, client_ip, created_at)
    WHERE incident_id IS NULL;

-- ---------------------------------------------------------------------------
-- updated_at maintenance (Alert + Incident triage / attach / explain)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_alerts_set_updated_at
    BEFORE UPDATE ON alerts
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_incidents_set_updated_at
    BEFORE UPDATE ON incidents
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Seed Application scope (§5.4 / Week 1 AC-3)
-- host_pattern is a regex: juice.lab.local + local curl share one app_id;
-- shop.lab.local is a second scope on the same Juice Shop upstream.
-- ---------------------------------------------------------------------------
INSERT INTO applications (name, host_pattern, risk_threshold, enabled)
VALUES
    ('Juice Shop', '^(juice\.lab\.local|localhost|127\.0\.0\.1)$', 60, TRUE),
    ('Juice Shop (shop)', '^shop\.lab\.local$', 60, TRUE);
