-- WAF Log Analyzer — MVP schema
-- Source of truth: docs/solution-design.md v1.6 §7.1 / §7.3
--
-- applications 1──N web_events 1──N detection_hits N──1 detection_rules
--                     │
--                     1
--                     │
--                     1 alerts N──1 incidents 1──N incident_work_notes
--
-- Alert is 1-1 with WebEvent and may be unattached (incident_id NULL)
-- until Incident Manager promotes it (IMMEDIATE / AGGREGATE).
-- Work notes are USER/SYSTEM insights persisted on the incident; they are
-- grounded context for LLM explain later (hits remain the detector evidence).

-- SOC auth — JWT access token is stateless; refresh token is persisted.
-- POST /api/oauth/tokens (solution-design §8).
-- RBAC maps RACI §10.2: operate / triage / edit rules.
-- Store SHA-256(token) only — never the raw refresh token.

-- ---------------------------------------------------------------------------
-- roles — one role per user (JWT claim `role`). Add rows here; do not hard-code in Java.
-- ---------------------------------------------------------------------------
CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(32) NOT NULL,
    name        VARCHAR(64) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_roles_code UNIQUE (code)
);

COMMENT
ON TABLE  roles IS 'SOC roles. JWT carries roles.code (ADMIN | ANALYST | VIEWER).';
COMMENT
ON COLUMN roles.code IS 'Stable identifier used in Spring @PreAuthorize / JWT. Uppercase, no spaces.';

-- ---------------------------------------------------------------------------
-- permissions — API capabilities (authority strings)
-- ---------------------------------------------------------------------------
CREATE TABLE permissions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64)  NOT NULL,
    name        VARCHAR(128) NOT NULL,
    description TEXT,

    CONSTRAINT uq_permissions_code UNIQUE (code)
);

COMMENT
ON TABLE  permissions IS 'Fine-grained authorities. Spring: hasAuthority(code).';
COMMENT
ON COLUMN permissions.code IS 'resource:action — e.g. rules:write, incidents:triage.';

CREATE TABLE role_permissions
(
    role_id       BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,

    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id)
);

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role_id       BIGINT       NOT NULL REFERENCES roles (id),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_users_username UNIQUE (username)
);

COMMENT
ON TABLE  users IS 'SOC operators. One role per user for a simple JWT role claim.';
COMMENT
ON COLUMN users.password_hash IS 'BCrypt (Spring BCryptPasswordEncoder).';

CREATE INDEX idx_users_role ON users (role_id);

-- ---------------------------------------------------------------------------
-- refresh_tokens
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash     CHAR(64)    NOT NULL,
    expires_at     TIMESTAMPTZ NOT NULL,
    revoked_at     TIMESTAMPTZ,
    replaced_by_id BIGINT REFERENCES refresh_tokens (id),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT chk_refresh_tokens_hash CHECK (token_hash ~ '^[0-9a-f]{64}$'
)
    );

COMMENT
ON TABLE  refresh_tokens IS 'Opaque refresh tokens for JWT rotation. Lookup by SHA-256 hex of the token presented by the client.';
COMMENT
ON COLUMN refresh_tokens.token_hash IS 'SHA-256 hex (lowercase) of the refresh token. Do not store plaintext.';
COMMENT
ON COLUMN refresh_tokens.revoked_at IS 'Set on logout, rotation, or reuse detection. NULL = still valid (until expires_at).';
COMMENT
ON COLUMN refresh_tokens.replaced_by_id IS 'Token issued in rotation; previous row stays for reuse detection.';

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_active ON refresh_tokens (user_id, expires_at) WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------------------
-- Seed roles (RACI: operate Compose / chỉnh rule / triage)
-- ---------------------------------------------------------------------------
INSERT INTO roles (code, name, description)
VALUES ('ADMIN', 'Administrator', 'Operate the lab, manage users and apps, CRUD detection rules, full SOC access.'),
       ('ANALYST', 'SOC Analyst',
        'Triage incidents (ACK/CLOSED), retry LLM explain, read events/alerts/rules. Cannot change rules or users.'),
       ('VIEWER', 'Viewer', 'Read-only dashboard, stats, and SSE. Cannot triage or mutate configuration.');

INSERT INTO permissions (code, name, description)
VALUES ('events:read', 'Read events', 'GET /api/events'),
       ('alerts:read', 'Read alerts', 'GET /api/alerts'),
       ('incidents:read', 'Read incidents', 'GET /api/incidents'),
       ('incidents:triage', 'Triage incidents', 'PATCH /api/incidents/{id} ACK|CLOSED'),
       ('incidents:explain', 'Retry LLM explain', 'POST /api/incidents/{id}/explain'),
       ('rules:read', 'Read detection rules', 'GET /api/rules'),
       ('rules:write', 'Write detection rules', 'POST/PATCH /api/rules'),
       ('apps:read', 'Read applications', 'GET /api/apps'),
       ('apps:write', 'Write applications', 'Create/update application scope'),
       ('stats:read', 'Read dashboard stats', 'GET /api/stats/overview'),
       ('stream:read', 'Realtime SSE', 'GET /api/stream/alerts|incidents'),
       ('users:read', 'Read users', 'List SOC users'),
       ('users:write', 'Write users', 'Create/disable SOC users');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         CROSS JOIN permissions p
WHERE r.code = 'ADMIN';

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         JOIN permissions p ON p.code IN (
                                          'events:read',
                                          'alerts:read',
                                          'incidents:read',
                                          'incidents:triage',
                                          'incidents:explain',
                                          'rules:read',
                                          'apps:read',
                                          'stats:read',
                                          'stream:read'
    )
WHERE r.code = 'ANALYST';

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         JOIN permissions p ON p.code IN (
                                          'events:read',
                                          'alerts:read',
                                          'incidents:read',
                                          'rules:read',
                                          'apps:read',
                                          'stats:read',
                                          'stream:read'
    )
WHERE r.code = 'VIEWER';

-- Lab seed accounts. Hashes are frozen once this V1 is applied; rotate via a
-- later migration if the database is reachable outside the lab.
INSERT INTO users (username, password_hash, role_id, enabled)
SELECT v.username, v.password_hash, r.id, TRUE
FROM (VALUES ('admin', '$2a$10$VK/3zutHF0iHi2S3kr8pxeTxWjqVFI2.Lkh1OBvGdIGHkPdw8jxx.', 'ADMIN'),
             ('analyst', '$2a$10$OktFZKz70mnUDxmKMA8Yceu9IbVgmxnsk.tPjLqEIapZEf3i8rz6K', 'ANALYST'),
             ('viewer', '$2a$10$5ULgWW/xEp1xtyhczkI.7uxBnwCasqZO2OmeeSEc5NnMpyqYKb.y6',
              'VIEWER')) AS v(username, password_hash, role_code)
         JOIN roles r ON r.code = v.role_code;

-- ---------------------------------------------------------------------------
-- applications — host → app_id scope (Juice Shop MVP, DVWA = phase 2)
-- ---------------------------------------------------------------------------
CREATE TABLE applications
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(128) NOT NULL,
    host_pattern   VARCHAR(255) NOT NULL,
    risk_threshold INTEGER      NOT NULL DEFAULT 60,
    enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_applications_host_pattern UNIQUE (host_pattern),
    CONSTRAINT chk_applications_risk_threshold
        CHECK (risk_threshold BETWEEN 0 AND 100)
);

COMMENT
ON TABLE  applications IS 'Monitored app scope. Normalize maps request host → app_id via host_pattern (regex).';
COMMENT
ON COLUMN applications.host_pattern IS 'Java/PostgreSQL regex matched against Nginx host (e.g. juice.lab.local).';
COMMENT
ON COLUMN applications.risk_threshold IS 'Alert when WebEvent.risk_score >= this value. Default 60 (§7.4).';

-- ---------------------------------------------------------------------------
-- detection_rules — runtime signatures (seeded from detection-rule-generator)
-- ---------------------------------------------------------------------------
CREATE TABLE detection_rules
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(255) NOT NULL,
    category          VARCHAR(32)  NOT NULL,
    pattern           TEXT         NOT NULL,
    target_field      VARCHAR(16)  NOT NULL,
    weight            INTEGER      NOT NULL,
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    description       TEXT,
    source            VARCHAR(16)  NOT NULL DEFAULT 'AI_MINED',
    generator_rule_id VARCHAR(64),
    rule_version      VARCHAR(32),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_detection_rules_code UNIQUE (code),
    CONSTRAINT chk_detection_rules_category
        CHECK (category IN ('SQLI', 'XSS', 'PATH_TRAVERSAL')),
    CONSTRAINT chk_detection_rules_target_field
        CHECK (target_field IN ('path', 'query', 'ua', 'raw')),
    CONSTRAINT chk_detection_rules_source
        CHECK (source IN ('HAND', 'AI_MINED')),
    CONSTRAINT chk_detection_rules_weight
        CHECK (weight BETWEEN 0 AND 100)
);

COMMENT
ON TABLE  detection_rules IS 'Compiled Java regex rules. Provenance: source, generator_rule_id, rule_version (§7.3.6).';
COMMENT
ON COLUMN detection_rules.target_field IS 'Access-log field only: path | query | ua | raw (lowercase).';
COMMENT
ON COLUMN detection_rules.source IS 'AI_MINED from rule-generator; HAND for manual supplements.';

CREATE INDEX idx_detection_rules_enabled ON detection_rules (enabled) WHERE enabled = TRUE;
CREATE INDEX idx_detection_rules_category ON detection_rules (category);

-- ---------------------------------------------------------------------------
-- web_events — canonical Nginx JSON access log (§5.4 / §7.1)
-- ---------------------------------------------------------------------------
CREATE TABLE web_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id         BIGINT       NOT NULL REFERENCES applications (id),
    event_time     TIMESTAMPTZ  NOT NULL,
    client_ip      INET         NOT NULL,
    method         VARCHAR(16)  NOT NULL,
    path           TEXT         NOT NULL,
    query          TEXT,
    status         INTEGER      NOT NULL,
    bytes_sent     BIGINT,
    request_time_s NUMERIC(10, 3),
    user_agent     TEXT,
    referer        TEXT,
    raw_ref        TEXT,
    host           VARCHAR(255) NOT NULL,
    risk_score     INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_web_events_status
        CHECK (status BETWEEN 100 AND 599),
    CONSTRAINT chk_web_events_risk_score
        CHECK (risk_score BETWEEN 0 AND 100),
    CONSTRAINT chk_web_events_bytes_sent
        CHECK (bytes_sent IS NULL OR bytes_sent >= 0),
    CONSTRAINT chk_web_events_request_time
        CHECK (request_time_s IS NULL OR request_time_s >= 0)
);

COMMENT
ON TABLE  web_events IS 'Normalized in-process from Kafka raw-web-logs. Score in-process then INSERT; updated_at covers a later risk_score patch if needed.';
COMMENT
ON COLUMN web_events.client_ip IS 'Nginx remote_addr as INET. Correlation key with app_id (§7.5).';
COMMENT
ON COLUMN web_events.bytes_sent IS 'Nginx body_bytes_sent (§5.4).';
COMMENT
ON COLUMN web_events.request_time_s IS 'Nginx request_time in seconds (§5.4).';
COMMENT
ON COLUMN web_events.raw_ref IS 'Kafka topic-partition-offset (or Filebeat metadata). Unique when present so redelivery does not duplicate the event.';
COMMENT
ON COLUMN web_events.risk_score IS '0–100 = min(100, base + freq_bonus(5m) + status_bonus) (§7.4).';

CREATE INDEX idx_web_events_app_time ON web_events (app_id, event_time DESC);
CREATE INDEX idx_web_events_app_ip_time ON web_events (app_id, client_ip, event_time DESC);
CREATE INDEX idx_web_events_client_time ON web_events (client_ip, event_time DESC);
CREATE INDEX idx_web_events_host ON web_events (host);
CREATE UNIQUE INDEX uq_web_events_raw_ref ON web_events (raw_ref) WHERE raw_ref IS NOT NULL;

-- ---------------------------------------------------------------------------
-- detection_hits — one row per (event, rule) match; evidence = matched snippet
-- Immutable after insert (weight is a snapshot). UNIQUE (event_id, rule_id)
-- already covers lookup by event_id.
-- ---------------------------------------------------------------------------
CREATE TABLE detection_hits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id   BIGINT      NOT NULL REFERENCES web_events (id) ON DELETE CASCADE,
    rule_id    BIGINT      NOT NULL REFERENCES detection_rules (id),
    evidence   TEXT        NOT NULL,
    weight     INTEGER     NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_detection_hits_event_rule UNIQUE (event_id, rule_id),
    CONSTRAINT chk_detection_hits_weight CHECK (weight BETWEEN 0 AND 100)
);

COMMENT
ON COLUMN detection_hits.weight IS 'Copied from detection_rules.weight at hit time so later CRUD does not rewrite history.';
COMMENT
ON COLUMN detection_hits.evidence IS 'Substring that matched the regex (for SOC drill-down / LLM explain).';

CREATE INDEX idx_detection_hits_rule ON detection_hits (rule_id);

-- ---------------------------------------------------------------------------
-- incidents — correlation key (app_id, client_ip); 1 incident : N alerts
-- Created before alerts so alerts.incident_id can FK here.
-- ---------------------------------------------------------------------------
CREATE TABLE incidents
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id                 BIGINT       NOT NULL REFERENCES applications (id),
    client_ip              INET         NOT NULL,
    severity               VARCHAR(16)  NOT NULL,
    score                  INTEGER      NOT NULL,
    alert_count            INTEGER      NOT NULL DEFAULT 0,
    title                  VARCHAR(255) NOT NULL,
    status                 VARCHAR(16)  NOT NULL DEFAULT 'OPEN',
    promote_reason         VARCHAR(16)  NOT NULL,
    explanation            TEXT,
    explanation_confidence VARCHAR(16),
    explanation_status     VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    explanation_error      TEXT,
    explained_at           TIMESTAMPTZ,
    opened_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    acked_at               TIMESTAMPTZ,
    closed_at              TIMESTAMPTZ,
    triaged_by             BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_incidents_severity
        CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT chk_incidents_status
        CHECK (status IN ('OPEN', 'ACK', 'CLOSED')),
    CONSTRAINT chk_incidents_promote_reason
        CHECK (promote_reason IN ('IMMEDIATE', 'AGGREGATE')),
    CONSTRAINT chk_incidents_explanation_confidence
        CHECK (explanation_confidence IS NULL
            OR explanation_confidence IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_incidents_explanation_status
        CHECK (explanation_status IN ('PENDING', 'READY', 'FAILED', 'SKIPPED')),
    CONSTRAINT chk_incidents_score
        CHECK (score BETWEEN 0 AND 100),
    CONSTRAINT chk_incidents_alert_count
        CHECK (alert_count >= 0),
    CONSTRAINT chk_incidents_ack
        CHECK (status <> 'ACK' OR acked_at IS NOT NULL),
    CONSTRAINT chk_incidents_closed
        CHECK (status <> 'CLOSED' OR closed_at IS NOT NULL)
);

COMMENT
ON TABLE  incidents IS 'SOC triage object. IMMEDIATE = CRITICAL; AGGREGATE = MEDIUM/HIGH with K=3 in window W=5m (§7.5). Never hard-delete; close instead.';
COMMENT
ON COLUMN incidents.severity IS 'max(member alert severities); updated when a new alert is attached.';
COMMENT
ON COLUMN incidents.score IS 'max(member alert scores).';
COMMENT
ON COLUMN incidents.explanation IS 'LLM explain output. Input is DetectionHit[] + incident_work_notes, not this column.';
COMMENT
ON COLUMN incidents.explanation_status IS 'LLM async: PENDING → READY|FAILED; SKIPPED when profile llm is off.';
COMMENT
ON COLUMN incidents.acked_at IS 'Set when status becomes ACK. Use for MTTA; do not use updated_at (also moves on explain/attach).';
COMMENT
ON COLUMN incidents.closed_at IS 'Set when status becomes CLOSED. Use for MTTR.';
COMMENT
ON COLUMN incidents.triaged_by IS 'Analyst who last ACK/CLOSED. NULL when auto-expired outside W.';

CREATE INDEX idx_incidents_app_status ON incidents (app_id, status, opened_at DESC);
CREATE INDEX idx_incidents_explain ON incidents (explanation_status);
-- At most one OPEN incident per correlation key. Close (or expire) OPEN rows
-- older than W=5m before inserting a new OPEN incident for the same key.
CREATE UNIQUE INDEX uq_incidents_open_key ON incidents (app_id, client_ip) WHERE status = 'OPEN';

-- ---------------------------------------------------------------------------
-- incident_work_notes — N-1 with incidents
-- USER = analyst insight (author_id required). SYSTEM = pipeline insight
-- (promote, attach, expire) with author_id NULL. Both are explain context.
-- LLM output stays on incidents.explanation — do not store it here.
-- ---------------------------------------------------------------------------
CREATE TABLE incident_work_notes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT      NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    author_id   BIGINT REFERENCES users (id),
    source      VARCHAR(16) NOT NULL,
    content     TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_incident_work_notes_source
        CHECK (source IN ('USER', 'SYSTEM')),
    CONSTRAINT chk_incident_work_notes_author
        CHECK ((source = 'SYSTEM') = (author_id IS NULL)),
    CONSTRAINT chk_incident_work_notes_content
        CHECK (length(btrim(content)) > 0)
);

COMMENT
ON TABLE  incident_work_notes IS 'Insights on an incident. USER/SYSTEM notes are grounded context for POST /api/incidents/{id}/explain; they are not the LLM explanation.';
COMMENT
ON COLUMN incident_work_notes.source IS 'USER = SOC analyst (author_id set). SYSTEM = Incident Manager / pipeline (author_id NULL).';
COMMENT
ON COLUMN incident_work_notes.author_id IS 'Required when source=USER. Disable the user rather than DELETE (FK RESTRICT).';
COMMENT
ON COLUMN incident_work_notes.content IS 'Free-text insight. Sanitize before sending to Ollama (same as DetectionHit evidence).';

CREATE INDEX idx_incident_work_notes_incident ON incident_work_notes (incident_id, created_at DESC);
CREATE INDEX idx_incident_work_notes_author ON incident_work_notes (author_id) WHERE author_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- alerts — 1-1 with web_events; incident_id NULL until promoted
-- ---------------------------------------------------------------------------
CREATE TABLE alerts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id      BIGINT       NOT NULL REFERENCES applications (id),
    event_id    BIGINT       NOT NULL REFERENCES web_events (id),
    incident_id BIGINT REFERENCES incidents (id) ON DELETE RESTRICT,
    client_ip   INET         NOT NULL,
    severity    VARCHAR(16)  NOT NULL,
    score       INTEGER      NOT NULL,
    title       VARCHAR(255) NOT NULL,
    summary     TEXT,
    status      VARCHAR(16)  NOT NULL DEFAULT 'OPEN',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_alerts_event UNIQUE (event_id),
    CONSTRAINT chk_alerts_severity
        CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT chk_alerts_status
        CHECK (status IN ('OPEN', 'ACK', 'CLOSED')),
    CONSTRAINT chk_alerts_score
        CHECK (score BETWEEN 0 AND 100)
);

COMMENT
ON TABLE  alerts IS 'Created when score >= application.risk_threshold. Always persisted; only a subset is promoted to an Incident.';
COMMENT
ON COLUMN alerts.incident_id IS 'NULL = not yet promoted (AGGREGATE count < K). RESTRICT delete so un-promoting cannot re-queue AGGREGATE.';
COMMENT
ON COLUMN alerts.status IS 'Feed-level copy. SOC triage is on Incident (§7.5); do not ACK/CLOSE an alert independently in MVP.';

CREATE INDEX idx_alerts_app_time ON alerts (app_id, created_at DESC);
CREATE INDEX idx_alerts_incident ON alerts (incident_id);
CREATE INDEX idx_alerts_status ON alerts (status);
CREATE INDEX idx_alerts_unattached ON alerts (app_id, client_ip, created_at) WHERE incident_id IS NULL;

-- ---------------------------------------------------------------------------
-- updated_at maintenance on every table that has the column
-- ---------------------------------------------------------------------------
CREATE
OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at
= NOW();
RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER trg_roles_set_updated_at
    BEFORE UPDATE
    ON roles
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_users_set_updated_at
    BEFORE UPDATE
    ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_refresh_tokens_set_updated_at
    BEFORE UPDATE
    ON refresh_tokens
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_applications_set_updated_at
    BEFORE UPDATE
    ON applications
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_detection_rules_set_updated_at
    BEFORE UPDATE
    ON detection_rules
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_web_events_set_updated_at
    BEFORE UPDATE
    ON web_events
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_alerts_set_updated_at
    BEFORE UPDATE
    ON alerts
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_incidents_set_updated_at
    BEFORE UPDATE
    ON incidents
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_incident_work_notes_set_updated_at
    BEFORE UPDATE
    ON incident_work_notes
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Seed Application scope (§5.4 / Week 1 AC-3)
-- host_pattern is a regex: juice.lab.local + local curl share one app_id;
-- shop.lab.local is a second scope on the same Juice Shop upstream.
-- ---------------------------------------------------------------------------
INSERT INTO applications (name, host_pattern, risk_threshold, enabled)
VALUES ('Juice Shop', '^(juice\.lab\.local|localhost|127\.0\.0\.1)$', 60, TRUE),
       ('Juice Shop (shop)', '^shop\.lab\.local$', 60, TRUE);
