-- SOC auth — JWT access token is stateless; refresh token is persisted.
-- POST /api/oauth/tokens (solution-design §8).
-- RBAC maps RACI §10.2: operate / triage / edit rules.
-- Store SHA-256(token) only — never the raw refresh token.

-- ---------------------------------------------------------------------------
-- roles — one role per user (JWT claim `role`). Add rows here; do not hard-code in Java.
-- ---------------------------------------------------------------------------
CREATE TABLE roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(32)   NOT NULL,
    name         VARCHAR(64)   NOT NULL,
    description  TEXT,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_roles_code UNIQUE (code)
);

COMMENT ON TABLE  roles IS 'SOC roles. JWT carries roles.code (ADMIN | ANALYST | VIEWER).';
COMMENT ON COLUMN roles.code IS 'Stable identifier used in Spring @PreAuthorize / JWT. Uppercase, no spaces.';

-- ---------------------------------------------------------------------------
-- permissions — API capabilities (authority strings)
-- ---------------------------------------------------------------------------
CREATE TABLE permissions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(64)   NOT NULL,
    name         VARCHAR(128)  NOT NULL,
    description  TEXT,

    CONSTRAINT uq_permissions_code UNIQUE (code)
);

COMMENT ON TABLE  permissions IS 'Fine-grained authorities. Spring: hasAuthority(code).';
COMMENT ON COLUMN permissions.code IS 'resource:action — e.g. rules:write, incidents:triage.';

CREATE TABLE role_permissions (
    role_id        BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_id  BIGINT NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,

    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id)
);

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)   NOT NULL,
    password_hash   VARCHAR(255)  NOT NULL,
    role_id         BIGINT        NOT NULL REFERENCES roles (id),
    enabled         BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_users_username UNIQUE (username)
);

COMMENT ON TABLE  users IS 'SOC operators. One role per user for a simple JWT role claim.';
COMMENT ON COLUMN users.password_hash IS 'BCrypt (Spring BCryptPasswordEncoder).';

CREATE INDEX idx_users_role ON users (role_id);

-- ---------------------------------------------------------------------------
-- refresh_tokens
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash      CHAR(64)      NOT NULL,
    expires_at      TIMESTAMPTZ   NOT NULL,
    revoked_at      TIMESTAMPTZ,
    replaced_by_id  BIGINT        REFERENCES refresh_tokens (id),
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT chk_refresh_tokens_hash CHECK (token_hash ~ '^[0-9a-f]{64}$')
);

COMMENT ON TABLE  refresh_tokens IS 'Opaque refresh tokens for JWT rotation. Lookup by SHA-256 hex of the token presented by the client.';
COMMENT ON COLUMN refresh_tokens.token_hash IS 'SHA-256 hex (lowercase) of the refresh token. Do not store plaintext.';
COMMENT ON COLUMN refresh_tokens.revoked_at IS 'Set on logout, rotation, or reuse detection. NULL = still valid (until expires_at).';
COMMENT ON COLUMN refresh_tokens.replaced_by_id IS 'Token issued in rotation; previous row stays for reuse detection.';

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_active ON refresh_tokens (user_id, expires_at)
    WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------------------
-- Seed roles (RACI: operate Compose / chỉnh rule / triage)
-- ---------------------------------------------------------------------------
INSERT INTO roles (code, name, description) VALUES
    ('ADMIN',   'Administrator', 'Operate the lab, manage users and apps, CRUD detection rules, full SOC access.'),
    ('ANALYST', 'SOC Analyst',   'Triage incidents (ACK/CLOSED), retry LLM explain, read events/alerts/rules. Cannot change rules or users.'),
    ('VIEWER',  'Viewer',        'Read-only dashboard, stats, and SSE. Cannot triage or mutate configuration.');

INSERT INTO permissions (code, name, description) VALUES
    ('events:read',        'Read events',           'GET /api/events'),
    ('alerts:read',        'Read alerts',           'GET /api/alerts'),
    ('incidents:read',     'Read incidents',        'GET /api/incidents'),
    ('incidents:triage',   'Triage incidents',      'PATCH /api/incidents/{id} ACK|CLOSED'),
    ('incidents:explain',  'Retry LLM explain',     'POST /api/incidents/{id}/explain'),
    ('rules:read',         'Read detection rules',  'GET /api/rules'),
    ('rules:write',        'Write detection rules', 'POST/PATCH /api/rules'),
    ('apps:read',          'Read applications',     'GET /api/apps'),
    ('apps:write',         'Write applications',    'Create/update application scope'),
    ('stats:read',         'Read dashboard stats',  'GET /api/stats/overview'),
    ('stream:read',        'Realtime SSE',          'GET /api/stream/alerts|incidents'),
    ('users:read',         'Read users',            'List SOC users'),
    ('users:write',        'Write users',           'Create/disable SOC users');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.code = 'ADMIN';

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'events:read',
    'alerts:read',
    'incidents:read',
    'incidents:triage',
    'incidents:explain',
    'rules:read',
    'apps:read',
    'stats:read',
    'stream:read'
)
WHERE r.code = 'ANALYST';

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'events:read',
    'alerts:read',
    'incidents:read',
    'rules:read',
    'apps:read',
    'stats:read',
    'stream:read'
)
WHERE r.code = 'VIEWER';

-- Lab seed accounts (change if the DB is reachable outside the lab).
INSERT INTO users (username, password_hash, role_id, enabled)
SELECT v.username, v.password_hash, r.id, TRUE
FROM (VALUES
    ('admin',   '$2a$10$VK/3zutHF0iHi2S3kr8pxeTxWjqVFI2.Lkh1OBvGdIGHkPdw8jxx.', 'ADMIN'),
    ('analyst', '$2a$10$OktFZKz70mnUDxmKMA8Yceu9IbVgmxnsk.tPjLqEIapZEf3i8rz6K', 'ANALYST'),
    ('viewer',  '$2a$10$5ULgWW/xEp1xtyhczkI.7uxBnwCasqZO2OmeeSEc5NnMpyqYKb.y6', 'VIEWER')
) AS v(username, password_hash, role_code)
JOIN roles r ON r.code = v.role_code;
