spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/waf_analyzer
    username: waf
    password: ${POSTGRES_PASSWORD:waf}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
