spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/waf_analyzer
    username: waf
    password: ${POSTGRES_PASSWORD:waf}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
